version: "3.8"

services:
  postgres:
    container_name: my_store_postgres_db
    image: "postgres:latest"
    restart: always
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_store
    ports:
      - 5432:5432
    volumes:
      - my-store-postgres-data:/var/lib/postgresql/data

  adminer:
    container_name: my_store_db_adminer
    restart: always
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - postgres

  # node_backend:
  #   container_name: my_store_node_backend
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 5000:5000 
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - ./backend/.env  

volumes:
  my-store-postgres-data:
